#!/bin/sh
#
#    00-header - create the header of the MOTD
#    Copyright (c) 2013 Nick Charlton
#    Copyright (c) 2009-2010 Canonical Ltd.
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi


HOSTNAME=$(hostname)
#METEOPIVER=$(cat /meteopi/VERSION)

#figlet $(hostname)
printf "\n\n"

printf "The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law."

printf "\n\n\n"
printf "\033[01;34m***********************************************************************\n"
printf "*                                                                     *\n"
printf "*       ███╗   ███╗███████╗████████╗███████╗ ██████╗ ██████╗ ██╗      *\n"
printf "*       ████╗ ████║██╔════╝╚══██╔══╝██╔════╝██╔═══██╗██╔══██╗██║      *\n"
printf "*       ██╔████╔██║█████╗     ██║   █████╗  ██║   ██║██████╔╝██║      *\n"
printf "*       ██║╚██╔╝██║██╔══╝     ██║   ██╔══╝  ██║   ██║██╔═══╝ ██║      *\n"
printf "*       ██║ ╚═╝ ██║███████╗   ██║   ███████╗╚██████╔╝██║     ██║      *\n"
printf "*       ╚═╝     ╚═╝╚══════╝   ╚═╝   ╚══════╝ ╚═════╝ ╚═╝     ╚═╝      *\n"
printf "*                                                                     *\n"
printf "***********************************************************************\n"

echo
echo

printf "\033[40;01;37;04mWelcome to %s - %s %s %s.\033[00;37m\n" "$HOSTNAME" "$DISTRIB_DESCRIPTION" "$(uname -v | cut -c1-4)" "$(uname -r)"
printf "\n"
